# Goal need to install the npm in ubuntu latest
name: Npm bulid
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm build
        run: npm run build
